version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Hala
      MYSQL_DATABASE: Bloomberg
      MYSQL_USER: root
      MYSQL_PASSWORD: Hala
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Bloomberg?autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hala
    depends_on:
      - db

volumes:
  db_data:
